# Generated by Django 2.0.13 on 2020-12-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GLCMtableModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrast', models.FloatField()),
                ('dissimilarity', models.FloatField()),
                ('homogeneity', models.FloatField()),
                ('energy', models.FloatField()),
                ('correlation', models.FloatField()),
                ('ass', models.FloatField()),
                ('lableclass', models.IntegerField()),
            ],
            options={
                'db_table': 'glcmtable',
            },
        ),
    ]
